version: 2.1

orbs:
  slack: circleci/slack@volatile
  clamav: ngs/clamav@dev:0.0.1

executors:
  cli:
    docker:
      - image: circleci/circleci-cli:0.1.2709

workflows:
  version: 2
  main:
    jobs:
      - lint
      - build
      - clamav/scan

      - dev-release:
          requires:
            - build
            - lint
            - clamav/scan
          context: orb-publishing

      - notify_slack:
          requires:
            - dev-release
          filters:
            branches:
              only: master
          context: orb-publishing

      - hold:
          type: approval
          requires:
            - notify_slack
          filters:
            branches:
              only: master

      - dev-promote-patch:
          requires:
            - hold
          filters:
            branches:
              only: master
          context: orb-publishing


jobs:
  lint:
    docker:
      - image: singapore/lint-condo
    steps:
      - checkout
      - run:
          'yamllint .'

  build:
    executor: cli
    steps:
      - checkout
      - run: "echo -e \"token: placeholder\nverbose: false > ~/.circleci/cli.yml\""
      - run: "sh scripts/validate-orbs.sh"

  dev-release:
    executor: cli
    steps:
      - checkout
      - run:
          name: Publish dev releases of any modified orbs
          command: |
            GIT_LOG=$(git log -1 --format="" --name-only)

            echo "Files changed:" $GIT_LOG

            bash scripts/dev-release.sh

  notify_slack:
    machine: true
    steps:
      - slack/notify:
          message: "Orbs from commit ${CIRCLE_SHA1} on the ${CIRCLE_BRANCH} branch are ready for review/approval: https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}"
          mentions: "${NGS_SLACK_UUID}"

  dev-promote-patch:
    executor: cli
    steps:
      - checkout

      - slack/notify:
          message: "Orb publishing was approved for any orbs modified in commit ${CIRCLE_SHA1} on the ${CIRCLE_BRANCH} branch: https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}"
          mentions: "${NGS_SLACK_UUID}"

      - run:
          name: Publish any modified orbs
          shell: /bin/bash -exo pipefail
          command: |
            GIT_LOG=$(git log -1 --format="" --name-only)

            echo "Files changed:" $GIT_LOG

            for ORB in src/*/; do
              orbname=$(basename $ORB)

              if [[ $(git log -1 --format="" --name-only | grep "$orbname") ]]; then

                echo "promoting ngs/${orbname}@dev:${CIRCLE_BRANCH}-${CIRCLE_SHA1} as patch release"

                circleci orb publish promote ngs/${orbname}@dev:${CIRCLE_BRANCH}-${CIRCLE_SHA1} patch --token $CIRCLECI_API_TOKEN
              else
                echo "${orbname} not modified; no need to promote"
              fi
            done
