version: 2.1

description: Swiftlint

jobs:
  run:
    description: Runs swiftlint
    executor: swiftlint
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml

executors:
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
