version: 2.1

description: Deploy artifacts to AWS S3

executors:
  awscli:
    docker:
      - image: quay.io/coreos/awscli:latest

commands:
  deploy:
    parameters:
      workspace:
        type: string
      artifacts:
        type: string
      bucket:
        type: string
      acl:
        type: string
        default: public-read
      cloudfront_distribution_id:
        type: string
        default: \"\"
      cloudfront_invalidation_paths:
        type: string
        default: '/*'
    steps:
      - attach_workspace:
          at: << parameters.workspace >>
      - run:
          name: Deploy
          command: aws s3 sync << parameters.workspace >>/<< parameters.artifacts >> s3://<< parameters.bucket >> --acl << parameters.acl >>
      - when:
          condition: <<parameters.cloudfront_distribution_id >>
          steps:
            - run:
                name: Invalidate CloudFront Distribution
                command: |
                  aws configure set preview.cloudfront true
                  aws cloudfront create-invalidation --distribution-id << parameters.cloudfront_distribution_id >> --paths << parameters.cloudfront_invalidation_paths >>
jobs:
  deploy:
    executor: awscli
    parameters:
      workspace:
        type: string
      artifacts:
        type: string
      bucket:
        type: string
      acl:
        type: string
        default: public-read
      cloudfront_distribution_id:
        type: string
        default: \"\"
      cloudfront_invalidation_paths:
        type: string
        default: '/*'
    steps:
      - deploy:
          workspace: << parameters.workspace >>
          artifacts: << parameters.artifacts >>
          bucket: << parameters.bucket >>
          acl: << parameters.acl >>
          cloudfront_distribution_id: << parameters.cloudfront_distribution_id >>
          cloudfront_invalidation_paths: << parameters.cloudfront_invalidation_paths >>

examples:
  main:
    description: Build and deploy
    usage:
      version: 2.1
      orbs:
        s3: ngs/s3-deploy@0.0.1
      jobs:
        build:
          executor: ...
          steps:
            - checkout
            - make
            - persist_to_workspace:
                root: .
                paths: [dist]
      workflows:
        main:
          jobs:
            - build
            - s3/deploy:
                requires: [build]
                filters:
                  branches:
                    only: master
                workspace: .
                artifacts: dist
                bucket: my-artifacts
                cloudfront_distribution_id: ABCDEFG
